//
//  UserData.swift
//  SwiftSheet
//
//  Created by Adnan Khan AdDY on 6/9/25.
//


public struct User: Identifiable {
    public var id: Int?
    public var name: String
    public var email: String
}

var users: [User] = [
    User(id: 1, name: "Adnan", email: "adnan1@example.com"),
    User(id: 2, name: "Ali", email: "ali2@example.com"),
    User(id: 3, name: "Sara", email: "sara3@example.com"),
    User(id: 4, name: "Zain", email: "zain4@example.com"),
    User(id: 5, name: "Fatima", email: "fatima5@example.com"),
    User(id: 6, name: "Omar", email: "omar6@example.com"),
    User(id: 7, name: "Hina", email: "hina7@example.com"),
    User(id: 8, name: "Usman", email: "usman8@example.com"),
    User(id: 9, name: "Ayesha", email: "ayesha9@example.com"),
    User(id: 10, name: "Bilal", email: "bilal10@example.com"),
    User(id: 11, name: "Yasir", email: "yasir11@example.com"),
    User(id: 12, name: "Nida", email: "nida12@example.com"),
    User(id: 13, name: "Kamran", email: "kamran13@example.com"),
    User(id: 14, name: "Maha", email: "maha14@example.com"),
    User(id: 15, name: "Rehan", email: "rehan15@example.com"),
    User(id: 16, name: "Adeel", email: "adeel16@example.com"),
    User(id: 17, name: "Mariam", email: "mariam17@example.com"),
    User(id: 18, name: "Tariq", email: "tariq18@example.com"),
    User(id: 19, name: "Hassan", email: "hassan19@example.com"),
    User(id: 20, name: "Iqra", email: "iqra20@example.com"),
    User(id: 21, name: "Noman", email: "noman21@example.com"),
    User(id: 22, name: "Anum", email: "anum22@example.com"),
    User(id: 23, name: "Faisal", email: "faisal23@example.com"),
    User(id: 24, name: "Noor", email: "noor24@example.com"),
    User(id: 25, name: "Imran", email: "imran25@example.com"),
    User(id: 26, name: "Sana", email: "sana26@example.com"),
    User(id: 27, name: "Kashif", email: "kashif27@example.com"),
    User(id: 28, name: "Hira", email: "hira28@example.com"),
    User(id: 29, name: "Rizwan", email: "rizwan29@example.com"),
    User(id: 30, name: "Ifrah", email: "ifrah30@example.com"),
    User(id: 31, name: "Zohaib", email: "zohaib31@example.com"),
    User(id: 32, name: "Neha", email: "neha32@example.com"),
    User(id: 33, name: "Wasif", email: "wasif33@example.com"),
    User(id: 34, name: "Alina", email: "alina34@example.com"),
    User(id: 35, name: "Junaid", email: "junaid35@example.com"),
    User(id: 36, name: "Rabia", email: "rabia36@example.com"),
    User(id: 37, name: "Zeeshan", email: "zeeshan37@example.com"),
    User(id: 38, name: "Lubna", email: "lubna38@example.com"),
    User(id: 39, name: "Shahzaib", email: "shahzaib39@example.com"),
    User(id: 40, name: "Mina", email: "mina40@example.com"),
    User(id: 41, name: "Rameez", email: "rameez41@example.com"),
    User(id: 42, name: "Mehwish", email: "mehwish42@example.com"),
    User(id: 43, name: "Faraz", email: "faraz43@example.com"),
    User(id: 44, name: "Zoya", email: "zoya44@example.com"),
    User(id: 45, name: "Jibran", email: "jibran45@example.com"),
    User(id: 46, name: "Tania", email: "tania46@example.com"),
    User(id: 47, name: "Naveed", email: "naveed47@example.com"),
    User(id: 48, name: "Areeba", email: "areeba48@example.com"),
    User(id: 49, name: "Haroon", email: "haroon49@example.com"),
    User(id: 50, name: "Zunaira", email: "zunaira50@example.com"),
    User(id: 51, name: "Shahid", email: "shahid51@example.com"),
    User(id: 52, name: "Aiman", email: "aiman52@example.com"),
    User(id: 53, name: "Kamil", email: "kamil53@example.com"),
    User(id: 54, name: "Sumbul", email: "sumbul54@example.com"),
    User(id: 55, name: "Basit", email: "basit55@example.com"),
    User(id: 56, name: "Aleena", email: "aleena56@example.com"),
    User(id: 57, name: "Owais", email: "owais57@example.com"),
    User(id: 58, name: "Shaista", email: "shaista58@example.com"),
    User(id: 59, name: "Waqas", email: "waqas59@example.com"),
    User(id: 60, name: "Tehmina", email: "tehmina60@example.com"),
    User(id: 61, name: "Nashit", email: "nashit61@example.com"),
    User(id: 62, name: "Arfa", email: "arfa62@example.com"),
    User(id: 63, name: "Umer", email: "umer63@example.com"),
    User(id: 64, name: "Nashra", email: "nashra64@example.com"),
    User(id: 65, name: "Haider", email: "haider65@example.com"),
    User(id: 66, name: "Fareeha", email: "fareeha66@example.com"),
    User(id: 67, name: "Qasim", email: "qasim67@example.com"),
    User(id: 68, name: "Aqsa", email: "aqsa68@example.com"),
    User(id: 69, name: "Sameer", email: "sameer69@example.com"),
    User(id: 70, name: "Zarmeen", email: "zarmeen70@example.com"),
    User(id: 71, name: "Taha", email: "taha71@example.com"),
    User(id: 72, name: "Rida", email: "rida72@example.com"),
    User(id: 73, name: "Abrar", email: "abrar73@example.com"),
    User(id: 74, name: "Laiba", email: "laiba74@example.com"),
    User(id: 75, name: "Danish", email: "danish75@example.com"),
    User(id: 76, name: "Bushra", email: "bushra76@example.com"),
    User(id: 77, name: "Majid", email: "majid77@example.com"),
    User(id: 78, name: "Zainab", email: "zainab78@example.com"),
    User(id: 79, name: "Saad", email: "saad79@example.com"),
    User(id: 80, name: "Momal", email: "momal80@example.com"),
    User(id: 81, name: "Furqan", email: "furqan81@example.com"),
    User(id: 82, name: "Mahnoor", email: "mahnoor82@example.com"),
    User(id: 83, name: "Asif", email: "asif83@example.com"),
    User(id: 84, name: "Sahar", email: "sahar84@example.com"),
    User(id: 85, name: "Kaleem", email: "kaleem85@example.com"),
    User(id: 86, name: "Ramsha", email: "ramsha86@example.com"),
    User(id: 87, name: "Naeem", email: "naeem87@example.com"),
    User(id: 88, name: "Tooba", email: "tooba88@example.com"),
    User(id: 89, name: "Sarmad", email: "sarmad89@example.com"),
    User(id: 90, name: "Mehreen", email: "mehreen90@example.com"),
    User(id: 91, name: "Faizan", email: "faizan91@example.com"),
    User(id: 92, name: "Zubaria", email: "zubaria92@example.com"),
    User(id: 93, name: "Talha", email: "talha93@example.com"),
    User(id: 94, name: "Nashrah", email: "nashrah94@example.com"),
    User(id: 95, name: "Ahsan", email: "ahsan95@example.com"),
    User(id: 96, name: "Anam", email: "anam96@example.com"),
    User(id: 97, name: "Ayaz", email: "ayaz97@example.com"),
    User(id: 98, name: "Roha", email: "roha98@example.com"),
    User(id: 99, name: "Waleed", email: "waleed99@example.com"),
    User(id: 100, name: "Hoor", email: "hoor100@example.com"),
]
